# Generated by Django 3.0.4 on 2020-03-19 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alias', models.CharField(default='-', max_length=20)),
                ('description', models.TextField()),
                ('author', models.CharField(default='N/A', max_length=20)),
                ('artist', models.CharField(default='N/A', max_length=20)),
                ('type_language', models.CharField(default='N/A', max_length=20)),
                ('year', models.CharField(default='N/A', max_length=20)),
                ('status', models.CharField(default='N/A', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='novel_pics')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('content', models.TextField(default='default')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Novel')),
            ],
        ),
    ]
