# Generated by Django 3.0.4 on 2020-03-19 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_novel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
