# Generated by Django 3.0.4 on 2020-03-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200321_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='artist',
        ),
    ]
