# Generated by Django 3.0.4 on 2020-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='type_language',
        ),
        migrations.AddField(
            model_name='novel',
            name='language',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
