# Generated by Django 3.0.4 on 2020-06-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='TL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Language'),
        ),
    ]
