# Generated by Django 3.0.4 on 2020-06-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_novel_tl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='language',
        ),
    ]
