# Generated by Django 3.0.4 on 2020-06-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_novel_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='TL',
            new_name='language',
        ),
    ]
