# Generated by Django 3.0.4 on 2020-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200626_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='novel',
            name='status',
        ),
    ]
