# Generated by Django 3.0.4 on 2020-06-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200626_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='language',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Language'),
        ),
    ]
