# Generated by Django 3.0.4 on 2020-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200626_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='uid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
