# Generated by Django 3.0.4 on 2020-06-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_novel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Status'),
        ),
    ]
