# Generated by Django 3.0.4 on 2020-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_novel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='uid',
            field=models.CharField(default='c8773cd375564d24a5370f4548944f8f', max_length=30),
        ),
    ]
