# Generated by Django 3.0.4 on 2020-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200626_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='uid',
            field=models.CharField(default='de605fe5f6734cf186fd471a2789a24d', editable=False, max_length=100),
        ),
    ]
