# Generated by Django 3.0.4 on 2020-06-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200626_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='alias',
        ),
    ]
