# Generated by Django 3.0.4 on 2020-08-21 01:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_novel_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.CreateModel(
            name='ChapterV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('content_path', models.CharField(default='default', max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Novel')),
            ],
        ),
    ]
