# Generated by Django 3.0.4 on 2020-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200821_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterv2',
            name='content_path',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='chapterv2',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
