# Generated by Django 3.1 on 2020-08-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200821_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Webnovel', max_length=500)),
                ('url', models.CharField(default='default', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='chapterv2',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.source'),
        ),
    ]
