# Generated by Django 3.1 on 2020-08-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200825_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterv2',
            name='source',
        ),
    ]
