# Generated by Django 3.1 on 2020-08-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_chapterv2_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterv2',
            name='source',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.source'),
        ),
    ]
