# Generated by Django 3.1 on 2020-08-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_chapterv2_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=500, upload_to='novel_pics'),
        ),
    ]
