# Generated by Django 3.1 on 2020-08-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200826_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='ChapterSource',
        ),
    ]
