# Generated by Django 3.1 on 2021-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_novel_wid'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='original',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
