# Generated by Django 3.1 on 2021-03-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210302_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterv2',
            name='source',
        ),
    ]
