# Generated by Django 3.1 on 2021-03-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_chapterv2_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='novel',
        ),
        migrations.DeleteModel(
            name='ChapterSource',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
