# Generated by Django 3.1 on 2021-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_chapterquepubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='dir_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
