# Generated by Django 3.1 on 2021-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_novel_dir_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='dir_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
