# Generated by Django 3.1 on 2021-04-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210422_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquepubs',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.novel'),
        ),
    ]
