# Generated by Django 3.1 on 2021-06-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_chapterquepubs_novel_qu'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterv2',
            name='in_other',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
