# Generated by Django 3.1 on 2021-07-01 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_chapterv2_in_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelqu',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='chapterquepubs',
            name='folder',
            field=models.CharField(default='novel_quepub/', max_length=500),
        ),
    ]
