# Generated by Django 3.1 on 2021-07-01 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20210701_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelqu',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
